---
- hosts: debian_vm
  become: true
  vars:
    package_list: "{{ lookup('file', 'wsl2_packages.txt').splitlines() }}"
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install essential packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - "{{ package_list }}"

    - name: Get current username
      command: whoami
      register: current_user

    - name: Copy .bashrc
      copy:
        src: ~/wsl2_configs/.bashrc
        dest: "/home/{{ current_user.stdout }}/.bashrc"
        owner: "{{ current_user.stdout }}"
        group: "{{ current_user.stdout }}"
        mode: '0644'

    - name: Copy .tmux.conf
      copy:
        src: ~/wsl2_configs/.tmux.conf
        dest: "/home/{{ current_user.stdout }}/.tmux.conf"
        owner: "{{ current_user.stdout }}"
        group: "{{ current_user.stdout }}"
        mode: '0644'

    - name: Copy .gitconfig
      copy:
        src: ~/wsl2_configs/.gitconfig
        dest: "/home/{{ current_user.stdout }}/.gitconfig"
        owner: "{{ current_user.stdout }}"
        group: "{{ current_user.stdout }}"
        mode: '0644'

